channels:
  - plotly
  - anaconda
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - anyio=4.3.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astor=0.8.1
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - autograd=1.5
  - autograd-gamma=0.5.0
  - babel=2.14.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.2
  - contourpy=1.0.5
  - cryptography=43.0.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.51.0
  - formulaic=0.6.2
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.9.0
  - future=0.18.3
  - gcsfs=2024.9.0
  - google-api-core=2.19.1
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.18.0
  - google-crc32c=1.5.0
  - google-resumable-media=2.7.1
  - googleapis-common-protos=1.63.2
  - graphlib-backport=1.0.3
  - grpcio=1.62.2
  - gseapy=0.9.5
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - html5lib=1.1
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - interface_meta=1.3.0
  - ipykernel=6.29.3
  - ipython=8.12.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonpointer=2.0
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.1
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcxx=16.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libxslt=1.1.41
  - libzlib=1.2.13
  - lifelines=0.27.8
  - llvm-openmp=14.0.6
  - lxml=5.2.1
  - lz4-c=1.9.4
  - markupsafe=2.0.1
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - multidict=6.0.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.3
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openjpeg=2.3.0
  - openpyxl=3.0.10
  - openssl=3.3.2
  - overrides=7.7.0
  - packaging=24.0
  - palettable=3.3.3
  - pandas=1.5.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - plotly=5.24.1
  - pooch=1.7.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - proto-plus=1.24.0
  - protobuf=4.25.3
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.22
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2024.1
  - pyyaml=6.0
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.34.0
  - requests=2.31.0
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.7.2
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.13.2
  - send2trash=1.8.3
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - tenacity=8.2.3
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.41.2
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - backports-zoneinfo==0.2.1
      - blitzgsea==1.3.47
      - brokenaxes==0.6.1
      - bx-python==0.13.0
      - cffi==1.17.1
      - comut==0.0.3
      - mpmath==1.3.0
      - pybigwig==0.3.22
      - qtl==0.1.8
      - rpy2==3.5.16
      - tqdm==4.66.5
      - tzlocal==5.2
